### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by NotSakura** [xgao28/financial_well_being_analysis#3]
Summary
Can't really tell what your paper is about as there is no abstract or introduction. It has something to do with financial well being score and the relation between that and financial skill and knowledge label
Strong positive points:
- you seem to have a lot of graphs especially the 4 graphs representing financial score seems to be super useful. If you were to add a little bit of context I think it would be really good!
Critical improvements needed:
Majority of the paper is unfinished so I guess just the very basics need to be fixed:
- Repo structure (there are certain things missing like download data script and sketches)
- LLM Usage
- models are also missing
- appendix with information is missing
Suggestions for improvement:
I think your graphs are off to a good start and your models are pretty good too.  all you have to do is provide context for what you are doing and why. What did you find out?
Make sure you include a download data script that will at least tell the reader how to get the data if it is downloaded from a link. 
Evaluation:
R/Python cited ([1]/1 pts)
Data cited ([1]/1 pts)
Class paper ([1]/1 pts)
LLM documentation ([1]/1 pts)
Title ([1]/2 pts)
[there but could use detail like what are you analysing?]
Author, date, and repo ([2]/2 pts)
[everything is there]
Abstract ([0]/4 pts)
[not there so maybe look at the rubric and follow the outline]
Introduction ([0]/4 pts)
[I can see the heading there so I assume you are getting to it right now]
Estimand ([0]/1 pts)
[I see the heading so just write a few sentences ]
Data ([1]/10 pts)
[You have some of the graphs there but it is missing a lot of info]
Measurement ([0]/4 pts)
[I don't see anything about this]
Model ([5]/10 pts)
[It is done and complete but a lot of the info is missing. What do the numbers mean and why do you do a regression model]
Results ([3]/10 pts)
[Nothing here except model summary which is good, but needs more like an explanation]
Discussion ([0]/10 pts)
[nothing here]
Prose ([4]/6 pts)
[nothing written so i guess no prose issue]
Cross-references ([1]/1 pts)
[i think its alright]
Captions ([1]/2 pts)
[could be more descriptive. you could have what is the main result from the grpahs or tables that you can see]
Graphs/tables/etc ([4]/4 pts)
[pretty good graphs]
Surveys, sampling, and observational data appendix ([0]/10 pts)
[nothing here]
Referencing ([2]/4 pts)
[some referencing there but, could include more especially in discussion section to back your analysis]
Commits ([2]/2 pts)
[pretty good]
Sketches ([0]/2 pts)
[not there]
Simulation ([4]/4 pts)
[there and pretty good]
Tests ([4]/4 pts)
[okay]
Parquet ([1]/1 pts)
[exists]
Reproducible workflow ([2]/4 pts)
[we don;t know how to download data]
Enhancements ([0]/4 pts)
[i didn't see a datasheet, shiny, model card or other things]
Miscellaneous ([0]/3 pts)
[not there]
Estimated overall mark:
41 / 100
Any other comments:
a lot of information is missing but it looks like a good start! I would say 2 things to be careful of. Make sure no code or warnings is outputted in pdf (it does for your first part). Next is that you should cite in data section and also should have a appendix for your own survey. Also when you cleaned the data there seems to be a lot of code. If you can find a way to reduce it down instead of manually coding each variable to be a factor.

**Comment by xgao28** [comment]
Thank you for your suggestion!
